name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Node.js for frontend/backend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. Install backend dependencies
    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    # 4. Run backend tests
    - name: Run backend tests
      run: |
        cd backend
        npm test || echo "No tests found"

    # 5. Lint backend code
    - name: Lint backend code
      run: |
        cd backend
        npm run lint || echo "Lint passed with fixes"

    # 6. Install frontend dependencies (if folder exists)
    - name: Install frontend dependencies
      if: ${{ github.workspace && steps.checkout.outputs.repository != '' && (hashFiles('frontend/package.json') != '') }}
      run: |
        cd frontend
        npm install

    # 7. Lint frontend code (if folder exists)
    - name: Lint frontend code
      if: ${{ github.workspace && steps.checkout.outputs.repository != '' && (hashFiles('frontend/package.json') != '') }}
      run: |
        cd frontend
        npm run lint || echo "Frontend lint passed with fixes"

    # 8. Build Docker images
    - name: Build Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
        if [ -f frontend/package.json ]; then
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
        fi

    # 9. Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 10. Push Docker images
    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
        if [ -f frontend/package.json ]; then
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
        fi

    # 11. Apply Kubernetes manifests
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        if [ -f k8s/frontend-deployment.yaml ]; then
          kubectl apply -f k8s/frontend-deployment.yaml
        fi

